import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Navbar17} from "@/components/header/Navbar17";
import {Contact14} from "@/components/contact/Contact14";
import {Footer6} from "@/components/footer/Footer6";

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    fallback: ['system-components', 'arial']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased container flex flex-col min-w-screen gap-16 mx-auto px-4 sm:px-6 lg:px-8`}
      >
      <header>
          <Navbar17 />
      </header>
      <main>{children}</main>
      <footer>
          <Contact14 />
          <Footer6 />
      </footer>
      </body>
    </html>
  );
}
